#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

ECHO_PREPEND="${0##*/} ==>"

echo "$ECHO_PREPEND START"

if ! [ "$(command -v pre-commit)" ]; then
    echo "$ECHO_PREPEND pre-commit not available"
    exit 1
fi

if ! [ -e ".git/hooks/pre-commit" ]; then
    echo "$ECHO_PREPEND installing the pre-commit script"
    pre-commit install
fi

if ! [ -d "node_modules" ]; then
    echo "$ECHO_PREPEND installing npm dependencies"
    npm install
fi

echo "$ECHO_PREPEND END"
