#!/bin/sh

# script/build: Build a distribution

set -e

cd "$(dirname "$0")/.."

ECHO_PREPEND="${0##*/} ==>"

echo "$ECHO_PREPEND START"

# if [ -d "dist" ]; then
#     echo "$ECHO_PREPEND removing dist dir"
#     rm -Rf dist
# fi

echo "$ECHO_PREPEND building dist"
npm run build

echo "$ECHO_PREPEND END"
