#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

ECHO_PREPEND="${0##*/} ==>"

echo "$ECHO_PREPEND START"

if [ -e ".git/hooks/pre-commit" ]; then
    echo "$ECHO_PREPEND uninstalling the pre-commit script"
    if [ "$(command -v pre-commit)" ]; then
        pre-commit uninstall
    else
        rm -v .git/hooks/pre-commit
    fi
fi

if [ -d "node_modules" ]; then
    echo "$ECHO_PREPEND removing npm dependencies"
    rm -Rf node_modules
fi

script/bootstrap

echo "$ECHO_PREPEND END"
